/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GpuLayout_ForceDirected */

#ifndef _Included_GpuLayout_ForceDirected
#define _Included_GpuLayout_ForceDirected
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GpuLayout_ForceDirected
 * Method:    ComputeGpuLayout
 * Signature: ([I[IIIIDIDD)[[F
 */
JNIEXPORT jobjectArray JNICALL Java_GpuLayout_ForceDirected_ComputeGpuLayout
  (JNIEnv *, jobject, jintArray, jintArray, jint, jint, jint, jdouble, jint, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
